### ISSUE TITLE
Update for this?

### ISSUE THREAD

**Issue by bphick** [openhomeautomation/adafruit-io-esp8266#1]
1/1/16
re: adafruit-io-esp8266/esp8266_lamp_module/esp8266_lamp_module.ino

There have been several changes to the MQTT library as well as Adafruit.io for this project.  I was just trying to get it to work for a Adafruit Huzzah ESP8266 and cannot.  Admittedly I was just tying to get an LED to light in response to the On OFF signal from the Adafruit dashboard by running it between pin 5 and ground (also with a resistor), or to get my meter to register a pulse... still nothing.

Is there away for a knowledgeable person to update this file to a working form?

**Comment by marcoschwartz** [comment]
Hi, there was a problem with the latest version of the ESP8266 library indeed, I just fixed that :) Let me know if the problem persists.

**Comment by bphick** [comment]
Now seems to work for me! Thanks for getting to it!
